import type { Metadata } from "next";
import { Inter, Merriweather } from "next/font/google";
import "@/styles/global.css";
import NavigationBar from "@/components/customComponents/NavigationBar";
import { ThemeProvider } from "@/components/providers/DarkModeProvider";
import Footer from "@/components/customComponents/Footer";
import AuthProviders from "@/components/providers/AuthProviders";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <AuthProviders>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavigationBar />
            {children}

            <Footer />
            <Toaster />
          </ThemeProvider>
        </AuthProviders>
      </body>
    </html>
  );
}
